In [1]:
using DataFrames

┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1278


In [2]:
df = DataFrame(A=1:4)

4×1 DataFrame
 Row │ A     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2
   3 │     3
   4 │     4

In [3]:
df

4×1 DataFrame
 Row │ A     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2
   3 │     3
   4 │     4

In [4]:
print(df)

4×1 DataFrame
 Row │ A     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2
   3 │     3
   4 │     4

In [5]:
A = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
A

3-element Array{Int64,1}:
 1
 2
 3

In [7]:
import SampleModule


LoadError: ArgumentError: Package SampleModule not found in current path:
- Run `import Pkg; Pkg.add("SampleModule")` to install the SampleModule package.


In [8]:
import Pkg

In [9]:
pwd()

"/Users/yilmaz/JuliaProjects/SampleModule/src"

In [10]:
cd("..")

In [11]:
pwd()

"/Users/yilmaz/JuliaProjects/SampleModule"

In [12]:
import SampleModule

LoadError: ArgumentError: Package SampleModule not found in current path:
- Run `import Pkg; Pkg.add("SampleModule")` to install the SampleModule package.


In [13]:
SampleModule.greet()

LoadError: UndefVarError: SampleModule not defined

In [14]:
pwd()


"/Users/yilmaz/JuliaProjects/SampleModule"

In [15]:
cd("src")

In [16]:
pwd()

"/Users/yilmaz/JuliaProjects/SampleModule/src"

In [17]:
using SampleModule

LoadError: ArgumentError: Package SampleModule not found in current path:
- Run `import Pkg; Pkg.add("SampleModule")` to install the SampleModule package.


In [18]:
cd("..")

In [19]:
Pkg.activate()

 Activating environment at `~/.julia/environments/JuliaPro_v1.5.4-1/Project.toml`


In [20]:
Pkg.activate(".")

 Activating environment at `~/JuliaProjects/SampleModule/Project.toml`


In [21]:
import SampleModule

┌ Info: Precompiling SampleModule [1e812adc-e85a-4424-b15a-f44f48f50046]
└ @ Base loading.jl:1278


Submodel testHello World!

In [22]:
SampleModule.greet()

Hello World!

In [23]:
A = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [24]:
mean(A)

LoadError: UndefVarError: mean not defined

In [25]:
using Statistics

In [26]:
mean(A)

2.0

In [27]:
df

4×1 DataFrame
 Row │ A     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2
   3 │     3
   4 │     4

In [28]:
df.B = ["M", "F","M", "F"]

4-element Array{String,1}:
 "M"
 "F"
 "M"
 "F"

In [29]:
df

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  M
   2 │     2  F
   3 │     3  M
   4 │     4  F

In [30]:
df["A"]

LoadError: ArgumentError: syntax df[column] is not supported use df[!, column] instead

In [31]:
df."A"

4-element Array{Int64,1}:
 1
 2
 3
 4

In [32]:
df[!,"A"]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [33]:
clms = [:A, :B]

2-element Array{Symbol,1}:
 :A
 :B

In [34]:
df[!,clms]

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  M
   2 │     2  F
   3 │     3  M
   4 │     4  F

In [35]:
names(df)

2-element Array{String,1}:
 "A"
 "B"

In [36]:
struct Point
    X:: Int
    Y:: Int
end

In [37]:
p = Point(1,2)

Point(1, 2)

In [38]:
p.X

1

In [51]:
mutable struct Point2
    X:: Real
    Y:: Real
    Point2(a,b) = new(a,b)
end

In [52]:
p2 = Point2(1.0,2.0)

Point2(1.0, 2.0)

In [53]:
p1.X

1.0

In [55]:
p2.X = 5.0

5.0

In [56]:
function update(P:: Point2,a,b)
    P.X = a
    P.Y = b
end

update (generic function with 1 method)

In [57]:
update(p2,10.0, 20.0)

20.0

In [58]:
p2.X

10.0

In [59]:
p2.Y

20.0

In [60]:
updateX(p:: Point2, a:: Real) = p.X = a

updateX (generic function with 1 method)

In [61]:
updateX(p2,15)

15

In [63]:
function f(x) 
    "original definition"
end

f (generic function with 1 method)

In [64]:
f(x::Int) = "definition for Int"

f (generic function with 2 methods)

In [65]:
f(1)


"definition for Int"

In [66]:
f(2.0)

"original definition"

In [67]:
x:: Int = 10

LoadError: syntax: type declarations on global variables are not yet supported

In [68]:
x = 10

10

In [69]:
typeof(x)

Int64

In [70]:
x

10

In [71]:
Pkg.add("Match")

   Updating registry at `~/.julia/registries/General`
###########################################################                81.1%################# 100.0%
   Updating registry at `~/.julia/registries/JuliaComputingRegistry`
  Resolving package versions...
  Installed p7zip_jll ─ v16.2.0+3
  Installed LibCURL ─── v0.6.3
  Installed Match ───── v1.1.0
  Installed Tar ─────── v1.9.0
  Installed Downloads ─ v1.4.0
  Installed TOML ────── v1.0.3
Updating `~/JuliaProjects/SampleModule/Project.toml`
  [7eb4fadd] + Match v1.1.0
Updating `~/JuliaProjects/SampleModule/Manifest.toml`
  [0dad84c5] - ArgTools
  [56f22d72] + Artifacts v1.3.0
  [f43a241f] - Downloads
  [b27032c2] - LibCURL
  [deac9b47] - LibCURL_jll
  [29816b5a] - LibSSH2_jll
  [7eb4fadd] + Match v1.1.0
  [c8ffd9c3] + MbedTLS_jll v2.16.8+1
  [14a3606d] - MozillaCACerts_jll
  [ca575930] - NetworkOptions
  [fa267f1f] - TOML
  [a4e569a6] - Tar
  [83775a58] - Zlib_jll
  [8e850ede] - nghttp2_jll
  [3f19e933] - p7zip_jll


LoadError: could not find entry with uuid f43a241f-c20a-4ad4-852c-f6b1247861c6 in manifest /Users/yilmaz/JuliaProjects/SampleModule/Manifest.toml

In [72]:
using Match

┌ Info: Precompiling Match [7eb4fadd-790c-5f42-8a69-bfa0b872bfbf]
└ @ Base loading.jl:1278


In [73]:
item = 1

1

In [74]:
@match item begin
   1 => "one"
   2 => "two"
   _ => "Something else..."
end

"one"

In [75]:
matchtype(item) = @match item begin
           n::Int               => println("Integers are awesome!")
           str::String          => println("Strings are the best")
           m::Dict{Int, String} => println("Ints for Strings?")
           d::Dict              => println("A Dict! Looking up a word?")
           _                    => println("Something unexpected")
   end

matchtype (generic function with 1 method)

In [76]:
matchtype(15)

Integers are awesome!


In [77]:
struct Address
    street::String
    city::String
    zip::String
end

struct Person
    firstname::String
    lastname::String
    address::Address
end

personinfo(person) = @match person begin
  Person("Julia", lname,  _)           => "Found Julia $lname"
  Person(fname, "Julia", _)            => "$fname Julia was here!"
  Person(fname, lname,
         Address(_, "Cambridge", zip)) => "$fname $lname lives in zip $zip"
  Person(_...)                         => "Unknown person!"
end

personinfo (generic function with 1 method)

In [78]:
personinfo(Person("Julia", "Robinson",Address("450 Serra Mall", "Stanford", "94305")))

"Found Julia Robinson"

In [81]:
mutable struct Employee 
    name::String
    salary::Real
    Employee(n,s) = new(n,s)
end

LoadError: invalid redefinition of constant Employee

In [85]:
mutable struct Employee1 
    name::String
    salary::Real
    Employee1(n,s=0) = new(n,s)
end

In [87]:
e = Employee1("Joe", 130)

Employee1("Joe", 130)

In [86]:
e1 = Employee1("tom")

Employee1("tom", 0)

In [88]:
Employee1() = Employee1("")

Employee1

In [89]:
e2 = Employee1()

Employee1("", 0)

In [90]:
v = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [91]:
@match v begin
    [a,b...] => "head is $a, tail is $b"
    _ => "something else"
end

"head is 1, tail is [2, 3]"

In [96]:
function append(L1,L2)
    @match L1 begin
       [] => return L2 
       [a,b...] => return [a,append(b,L2)]
        _ => "error"
    end
end

append (generic function with 1 method)

In [95]:
append([],[1,2,3])

3-element Array{Int64,1}:
 1
 2
 3

In [98]:
y = append([1],[2,3])

2-element Array{Any,1}:
 1
  [2, 3]

In [99]:
y

2-element Array{Any,1}:
 1
  [2, 3]

In [101]:
using Base.Iterators

In [104]:
Base.Iterators.flatten([1,[2,3]])

Base.Iterators.Flatten{Array{Any,1}}(Any[1, [2, 3]])

In [106]:
import Pkg
Pkg.add("BenchmarkTools")

  Resolving package versions...
  Installed BenchmarkTools ─ v0.6.0
Updating `~/JuliaProjects/SampleModule/Project.toml`
  [6e4b80f9] + BenchmarkTools v0.6.0
Updating `~/JuliaProjects/SampleModule/Manifest.toml`
  [6e4b80f9] + BenchmarkTools v0.6.0


In [107]:
using BenchmarkTools
 
flat(arr) = mapreduce(x -> x == [] || x[1] === x ? x : flat(x), vcat, arr, init=[])

┌ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
└ @ Base loading.jl:1278


flat (generic function with 1 method)

In [108]:
flat([1,[2,3]])

3-element Array{Any,1}:
 1
 2
 3

In [109]:
z = [1]

1-element Array{Int64,1}:
 1

In [110]:
z[1] === z

false

In [114]:
map(x -> x[1] === x ? println(x) : "",[1,2,3])

1
2
3


3-element Array{Nothing,1}:
 nothing
 nothing
 nothing

In [115]:
x = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [116]:
x[1] === 1

true

In [117]:
a = x[1]

1

In [118]:
x[1] === x

false

In [119]:
function append(L1,L2)
    @match L1 begin
       [] => return L2 
       [a,b...] => return flat([a,append(b,L2)])
        _ => "error"
    end
end

append (generic function with 1 method)

In [120]:
append([1,2,3],[4,5,6])

6-element Array{Any,1}:
 1
 2
 3
 4
 5
 6

In [5]:
Pkg.add("PyCall")

  Resolving package versions...
Updating `~/.julia/environments/JuliaPro_v1.5.4-1/Project.toml`
  [438e738f] + PyCall v1.92.2
Updating `~/.julia/environments/JuliaPro_v1.5.4-1/Manifest.toml`
  [438e738f] + PyCall v1.92.2


In [6]:
using PyCall
math = pyimport("math")
math.sin(math.pi / 4)

0.7071067811865475

In [7]:
math = pyimport("math")
math.sin(math.pi / 4)

0.7071067811865475

In [124]:
math.sin(math.pi / 4)

0.7071067811865475

In [8]:
pwd()

"/Users/yilmaz/JuliaProjects/SampleModule/src"

In [10]:
py"""
import numpy as np

def sinpi(x):
    return np.sin(np.pi * x)
"""
py"sinpi"(1)

1.2246467991473532e-16

In [130]:
pwd()

"/Users/yilmaz/JuliaProjects/SampleModule/src"

In [141]:
using Conda

LoadError: ArgumentError: Package Conda not found in current path:
- Run `import Pkg; Pkg.add("Conda")` to install the Conda package.


In [2]:
import Pkg; Pkg.add("Conda")

   Updating registry at `~/.julia/registries/General`
tar: Failed to set default locale
tar: Failed to set default locale
######################################################################### 100.0%
tar: Failed to set default locale
   Updating registry at `~/.julia/registries/JuliaComputingRegistry`
  Resolving package versions...
Updating `~/.julia/environments/JuliaPro_v1.5.4-1/Project.toml`
  [8f4d0f93] + Conda v1.5.1
No Changes to `~/.julia/environments/JuliaPro_v1.5.4-1/Manifest.toml`


In [4]:
using Conda

In [145]:
py"""
import numpy as np

def sinpi(x):
    return np.sin(np.pi * x)
"""
py"sinpi"(1)

1.2246467991473532e-16

In [148]:
using Conda


In [150]:
Conda.add("scipy")

┌ Info: Running `conda install -y scipy` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:128


Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/yilmaz/.julia/conda/3

  added / updated specs:
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.1          |       h93005f0_2         426 KB
    scipy-1.6.2                |   py38h2515648_0        14.5 MB
    ------------------------------------------------------------
                                           Total:        15.0 MB

The following NEW packages will be INSTALLED:

  libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  scipy              pkgs/main/osx-64::scipy-1.6.2-py38h2515648_0



libgfortran-3.0.1    | 426 KB    | #################################### | 100% 
scipy-1.6.2          | 14.5 MB   | #################################### | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing tra

In [151]:
so = pyimport("scipy.optimize")

PyObject <module 'scipy.optimize' from '/Users/yilmaz/.julia/conda/3/lib/python3.8/site-packages/scipy/optimize/__init__.py'>

In [178]:
py"""
import numpy as np
import math
from scipy.optimize import brentq

def get_antropogenic_release(xt, c1, c2, r1, r2, w1):
    rule = w1 * (abs(xt - c1) / r1) ** 3 + (1 - w1) * (abs(xt - c2) / r2) ** 3
    at1 = max(rule, 0.01)
    at = min(at1, 0.1)

    return at

def lake_model(b=0.42, q=2.0, mean=0.02,
               stdev=0.001, delta=0.98, alpha=0.4,
               nsamples=100, myears=100, c1=0.25,
               c2=0.25, r1=0.5, r2=0.5,
               w1=0.5, seed=None):

    '''runs the lake model for nsamples stochastic realisation using
    specified random seed.

    Parameters
    ----------
    b : float
        decay rate for P in lake (0.42 = irreversible)
    q : float
        recycling exponent
    mean : float
            mean of natural inflows
    stdev : float
            standard deviation of natural inflows
    delta : float
            future utility discount rate
    alpha : float
            utility from pollution
    nsamples : int, optional
    myears : int, optional
    c1 : float
    c2 : float
    r1 : float
    r2 : float
    w1 : float
    seed : int, optional
           seed for the random number generator

    Returns
    -------
    tuple

    '''

    np.random.seed(seed)
    Pcrit = brentq(lambda x: x ** q / (1 + x ** q) - b * x, 0.01, 1.5)

    X = np.zeros((myears,))
    average_daily_P = np.zeros((myears,))
    reliability = 0.0
    inertia = 0
    utility = 0

    for _ in range(nsamples):
        X[0] = 0.0
        decision = 0.1

        decisions = np.zeros(myears, )
        decisions[0] = decision

        natural_inflows = np.random.lognormal(
            math.log(mean ** 2 / math.sqrt(stdev ** 2 + mean ** 2)),
            math.sqrt(math.log(1.0 + stdev ** 2 / mean ** 2)),
            size=myears)

        for t in range(1, myears):
            # here we use the decision rule
            decision = get_antropogenic_release(X[t - 1], c1, c2, r1, r2, w1)
            decisions[t] = decision

            X[t] = (1 - b) * X[t - 1] + X[t - 1] ** q / (1 + X[t - 1] ** q) + decision + \
                   natural_inflows[t - 1]
            average_daily_P[t] += X[t] / nsamples

        reliability += np.sum(X < Pcrit) / (nsamples * myears)
        inertia += np.sum(np.absolute(np.diff(decisions)
                                      < 0.02)) / (nsamples * myears)
        utility += np.sum(alpha * decisions * np.power(delta,
                                                       np.arange(myears))) / nsamples
    max_P = np.max(average_daily_P)
    return max_P, utility, inertia, reliability


"""

In [179]:
py"lake_model"()

(0.12260956593140497, 0.35548981030647125, 0.9900000000000014, 1.0000000000000007)

In [158]:
pwd()


"/Users/yilmaz/JuliaProjects/SampleModule/src"

In [161]:
cd("..")

In [162]:
pwd()


"/Users/yilmaz/JuliaProjects/SampleModule"

In [181]:
Conda.pip_interop(true, Conda.ROOTENV)

┌ Info: Running `conda config --set pip_interop_enabled true --file /Users/yilmaz/.julia/conda/3/condarc-julia.yml` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:128


In [177]:
Conda.ROOTENV

"/Users/yilmaz/.julia/conda/3"

In [182]:
Conda.pip_interop(true, Conda.ROOTENV)

┌ Info: Running `conda config --set pip_interop_enabled true --file /Users/yilmaz/.julia/conda/3/condarc-julia.yml` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:128


In [183]:
Conda.pip("install", "ema_workbench")

┌ Info: Running `pip install ema_workbench` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:448


  Using cached ema_workbench-2.0.8.tar.gz (23.7 MB)
  Created wheel for ema-workbench: filename=ema_workbench-2.0.8-py3-none-any.whl size=23772557 sha256=4fad45c86a53cb7ad204637f287f01f74a56a5c70051a949c7bed739a6545bee
  Stored in directory: /Users/yilmaz/Library/Caches/pip/wheels/b6/73/3e/9bedda01ebbc0a1b247c1890f6607ae8c1a66f7f94c0cda60e
Successfully built ema-workbench


In [185]:
Conda.pip("install", "altair")

┌ Info: Running `pip install altair` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:448


  Using cached altair-4.1.0-py3-none-any.whl (727 kB)


In [186]:
Conda.add("ipyparallel")

┌ Info: Running `conda install -y ipyparallel` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:128


Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/yilmaz/.julia/conda/3

  added / updated specs:
    - ipyparallel


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipyparallel-6.3.0          |   py38hecd8cb5_0         308 KB
    ------------------------------------------------------------
                                           Total:         308 KB

The following NEW packages will be INSTALLED:

  ipyparallel        pkgs/main/osx-64::ipyparallel-6.3.0-py38hecd8cb5_0



ipyparallel-6.3.0    | 308 KB    | #################################### | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


In [188]:
Conda.pip("install", "SALib")

┌ Info: Running `pip install SALib` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:448


  Using cached SALib-1.3.12.tar.gz (855 kB)
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
  Created wheel for SALib: filename=SALib-1.3.12-py2.py3-none-any.whl size=729049 sha256=1c8e0b957775e7efee22fbc6689dcb88f67a22f2191cd244fa4f8778861d6af8
  Stored in directory: /Users/yilmaz/Library/Caches/pip/wheels/b4/09/e4/f48a332b3e48dc39ee8fa92fdd0d92855c3e78fe391cdbde8b
Successfully built SALib


In [189]:
Conda.pip("install", "platypus-opt")

┌ Info: Running `pip install platypus-opt` in root environment
└ @ Conda /Users/yilmaz/.julia/packages/Conda/tJJuN/src/Conda.jl:448


  Using cached Platypus_Opt-1.0.4-py3-none-any.whl (70 kB)


In [190]:
lake_model

LoadError: UndefVarError: lake_model not defined

In [191]:
py"lake_model"()

(0.12264454454151613, 0.355381921617503, 0.9900000000000014, 1.0000000000000007)

In [203]:
py"""
from ema_workbench import (Model, RealParameter, MultiprocessingEvaluator, CategoricalParameter,
                           IntegerParameter, ScalarOutcome, ArrayOutcome, Constant, ema_logging,
                           perform_experiments)
from ema_workbench.em_framework.evaluators import (MC, LHS, SOBOL)

ema_logging.log_to_stderr(ema_logging.INFO)

model = Model('lakeproblem', function=lake_model)

model.uncertainties = [RealParameter('b', 0.1, 0.45),
                           RealParameter('q', 2.0, 4.5),
                           RealParameter('mean', 0.01, 0.05),
                           RealParameter('stdev', 0.001, 0.005),
                           RealParameter('delta', 0.93, 0.99)]

model.levers = [RealParameter("c1", -2, 2),
                    RealParameter("c2", -2, 2),
                    RealParameter("r1", 0, 2),
                    RealParameter("r2", 0, 2),
                    RealParameter("w1", 0, 1)]

 
model.outcomes = [ScalarOutcome('max_P'),
                      ScalarOutcome('utility'),
                      ScalarOutcome('inertia'),
                      ScalarOutcome('reliability')]

# override some of the defaults of the model
model.constants = [Constant('alpha', 0.41),
                       Constant('nsamples', 150),
                       Constant('myears', 100)]

n_contextScenarios = 5
n_designPolicies = 5

res = perform_experiments(model, n_contextScenarios, n_designPolicies, levers_sampling=LHS)
experiments, outcomes = res

experiments.to_csv('experiment.csv')

"""

[MainProcess/INFO] performing 5 scenarios * 5 policies * 1 model(s) = 25 experiments
[MainProcess/INFO] performing experiments sequentially
[MainProcess/INFO] 2 cases completed
[MainProcess/INFO] 4 cases completed
[MainProcess/INFO] 6 cases completed
[MainProcess/INFO] 8 cases completed
[MainProcess/INFO] 10 cases completed
[MainProcess/INFO] 12 cases completed
[MainProcess/INFO] 14 cases completed
[MainProcess/INFO] 16 cases completed
[MainProcess/INFO] 18 cases completed
[MainProcess/INFO] 20 cases completed
[MainProcess/INFO] 22 cases completed
[MainProcess/INFO] 24 cases completed
[MainProcess/INFO] experiments finished


In [201]:
pwd()

"/Users/yilmaz/JuliaProjects/SampleModule"

In [17]:
struct Model{F}
    f::F
end


In [18]:

(m::Model)(x) = m.f(x)

In [19]:
m2 = Model(x->2x)

Model{var"#7#8"}(var"#7#8"())

In [35]:
Model(x->2x)(10)

20

In [21]:
macro unless(test_expr, branch_expr)
  quote
    if !$test_expr
      $branch_expr
    end
  end
end

@unless (macro with 1 method)

In [22]:
array = [1, 2, 'b']
@unless 3 in array println("array does not contain 3")

array does not contain 3


In [29]:
FT = ((:f1, [(:f2, [:f21,:f23]),:f3]),(:f4))

((:f1, Any[(:f2, [:f21, :f23]), :f3]), :f4)

In [30]:
x = :(1+1)

:(1 + 1)

In [31]:
eval(x)

2

In [32]:
FT[1]

(:f1, Any[(:f2, [:f21, :f23]), :f3])

In [33]:
FT[1][1]

:f1

In [34]:
@unless 3 in array begin
    println("Line1")
    println("Line2")
end

Line1
Line2


In [36]:
FT0 = ((:f1,[]),(:f2,[]))

((:f1, Any[]), (:f2, Any[]))

In [86]:
macro feature(base,featureList) 
   quote
        if ($featureList == []) eval(Expr(:call, $base,10))
        else 
            for i in $featureList
                println(i)
            end
        end
        
    end
end

@feature (macro with 1 method)

In [87]:
@feature x->2*x [:f1,:f2]

f1
f2


In [89]:
import Pkg; Pkg.add("Match")


  Resolving package versions...
Updating `~/.julia/environments/JuliaPro_v1.5.4-1/Project.toml`
  [7eb4fadd] + Match v1.1.0
Updating `~/.julia/environments/JuliaPro_v1.5.4-1/Manifest.toml`
  [7eb4fadd] + Match v1.1.0


In [90]:
using Match

In [165]:
FT = [[:f1,[:f11,[:f111,:f112]],[:f12,[:f121,:f122]]],[:f2]]

2-element Array{Array{Any,1},1}:
 [:f1, Any[:f11, [:f111, :f112]], Any[:f12, [:f121, :f122]]]
 [:f2]

In [212]:
function visitor(ft,L)
    @match ft begin
        [] => nothing
        [a,b...], if typeof(a)==Symbol end => begin
            L = [L;a]
            if (b != []) L = visitor(b,L) end
            return L
        end
        [a,b...] => begin
            L = visitor(a,L)
            if (b != []) L = visitor(b,L) end
            return L
        end
        _ =>  return []
    end
end

visitor (generic function with 2 methods)

In [213]:
S = visitor(FT,[])

8-element Array{Any,1}:
 :f1
 :f11
 :f111
 :f112
 :f12
 :f121
 :f122
 :f2

In [167]:
S

8-element Array{Any,1}:
 :f1
 :f11
 :f111
 :f112
 :f12
 :f121
 :f122
 :f2

In [114]:
A = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [116]:
@match A begin
   [a,b...] => 
        begin
            println(a) 
            println(b)
        end
    _ => nothing
end

1
[2, 3]


In [133]:
A

3-element Array{Int64,1}:
 1
 2
 3

In [251]:
function FG1(x) 
    a = x + 1 
    a
end

FG1 (generic function with 1 method)

In [252]:
FG1(5)

6

In [253]:
expr = Expr(:call, :FG1, 5)
eval(expr)

6

In [214]:
struct Point
           x::Int
           y
       end

In [216]:
fnames = fieldnames(Point)

(:x, :y)

In [218]:
fnames[1]

:x

In [314]:
methods(f1)

# 2 methods for generic function "f1":
[1] f1(x::Int64) in Main at In[179]:1
[2] f1(x) in Main at In[246]:1

In [315]:
macro feature(base,featureList) 
   quote
        if ($featureList == []) eval(Expr(:call, $base,10))
        else 
            for i in $featureList
                println(i)
            end
        end
        
    end
end

@feature (macro with 1 method)

In [318]:
@feature FG1 []

11

In [321]:
a = quote
        struct Point6
            x
            y
            z
        end
    
        struct Model{F}
            f::F
        end
end
end

quote
    #= In[321]:2 =#
    struct Point6
        #= In[321]:3 =#
        x
        #= In[321]:4 =#
        y
        #= In[321]:5 =#
        z
    end
    #= In[321]:8 =#
    function test(a)
        #= In[321]:8 =#
        #= In[321]:9 =#
        a
    end
end

In [322]:
eval(a)

test (generic function with 1 method)

In [323]:
test(3)

3

In [377]:
macro testGen1(sname,modelname,funcname)
    quote
        struct $sname
            x
            y
            z
        end

        struct $modelname{F}
            $f::F
        end
        
        $modelname($funcname)
end
    
end

@testGen1 (macro with 1 method)

In [392]:
func1 = p -> println(p.x)
@testGen Point9 Point9Model func1

In [393]:
p = Point9(1,2,3)

Point9(1, 2, 3)

In [380]:
fieldnames(Point9Model)

(:func1,)

In [386]:
fn = fieldnames(Point9Model)

(:func1,)

In [387]:
fn[1]

:func1

In [394]:
eval(Expr(:call, fn[1], p))

1


In [395]:
length(fn)

1